npmAuthToken: ${NPM_TOKEN}
yarnPath: '.yarn/releases/yarn-berry.js'
packageExtensions:
  'styled-components@*':
    dependencies:
      'react-is': '*'
  '@mdx-js/react@*':
    dependencies:
      'react': '*'
  '@storybook/addon-essentials@*':
    dependencies:
      '@storybook/components': '*'
      '@storybook/core-events': '*'
      '@storybook/theming': '*'
  '@storybook/addon-postcss@*':
    dependencies:
      'webpack': '*'
  '@storybook/core@*':
    dependencies:
      'webpack': '*'
  '@storybook/csf-tools@*':
    dependencies:
      '@babel/core': '*'
  'react-dev-utils@*':
    dependencies:
      'typescript': '*'
      'webpack': '*'
