version: 2.1

orbs:
  node: circleci/node@4.1
  gh-pages: sugarshin/gh-pages@0.0.6

jobs:
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install
          command: npx pnpm install
      - run:
          name: Test
          command: npm run test:lib
  library:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install
          command: npx pnpm install
      - run:
          name: Build
          command: npm run build:lib
      - run:
          name: Deploy
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
            npm publish --access=public --tolerate-republish
  storybook:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install
          command: npx pnpm install
      - run:
          name: Build
          command: npm run build:storybook
      - gh-pages/deploy:
          build-dir: dist/storybook

workflows:
  main:
    jobs:
      - test
      - library:
          requires:
            - test
          filters:
            branches:
              only: main
      - storybook:
          requires:
            - test
          filters:
            branches:
              only: main
