name: Main
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test

      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: false
          start: yarn start:demo
          command: yarn test:e2e

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
