name: Main
on:
  push:
    branches:
      - main
jobs:
  library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build:lib
      - name: Publish library
        run: |
          echo "npmAuthToken: ${{ secrets.NPM_TOKEN }}" >> .yarnrc.yml
          yarn npm publish --access=public --tolerate-republish
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build:storybook
      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/storybook
