name: Branch
on: pull_request
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
